# Generated by Django 2.0.7 on 2019-11-10 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='toke',
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(default='', max_length=50, verbose_name='Pre id'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_num',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='id'),
        ),
    ]
