# Generated by Django 2.0.7 on 2019-11-10 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20191110_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, default='patient@patient', max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('photo', models.ImageField(blank=True, default='null.png', upload_to='')),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.Token', verbose_name='Id')),
            ],
        ),
    ]
