# Generated by Django 2.0.7 on 2019-11-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='cms', max_length=50, verbose_name='Pre id'),
        ),
    ]
