# Generated by Django 2.0.7 on 2019-11-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20191110_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='pa@pt.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medical.Token'),
        ),
    ]
