# Generated by Django 2.0.7 on 2019-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20191110_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
