# Generated by Django 2.0.7 on 2019-11-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_auto_20191110_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='token',
        ),
    ]
