# Generated by Django 2.0.7 on 2019-11-10 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_remove_patient_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
        ),
    ]
