# Generated by Django 2.0.7 on 2019-11-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20191110_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_appointment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='Patient Queue', max_length=100, verbose_name='Your Note')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.Patient')),
            ],
        ),
    ]
