# Generated by Django 2.0.7 on 2019-11-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_patientqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientqueue',
            old_name='appointment',
            new_name='appointmenttime',
        ),
    ]
