# Generated by Django 2.0.7 on 2019-11-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_auto_20191111_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientqueue',
            old_name='appointmenttime',
            new_name='appointment_time',
        ),
    ]
