# Generated by Django 2.0.7 on 2019-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_medicalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='histroy',
            field=models.TextField(verbose_name='Medical History'),
        ),
    ]
