# Generated by Django 2.0.7 on 2019-11-12 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_auto_20191112_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date_of_record',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 12, 13, 23, 5, 6521)),
            preserve_default=False,
        ),
    ]
