# Generated by Django 2.0.7 on 2019-11-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20191109_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dr',
            field=models.BooleanField(default=False),
        ),
    ]
