# Generated by Django 2.0.7 on 2019-11-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_user_is_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_dr',
            field=models.BooleanField(default=False, verbose_name='Is Doctor'),
        ),
    ]
